### ISSUE TITLE
Feature request: `tyscan console`

### ISSUE THREAD

**Issue by wata727** [sider/TyScan#10]
TyScan's matching system using types is complicated, so if we have features like REPL will be useful for building patterns. Please image something like [`querly console`](https://github.com/soutaro/querly#configuration). What do you think?

**Comment by tomokinakamaru** [comment]
The implementation is still in progress, but the simplest version of `console` is available at the branch `https://github.com/sider/TyScan/tree/fix/issue10`. Any kinds of requests or feedback are more than welcome!

The GIF below shows how the current version works:
![gAmCx8ZqXZ](https://user-images.githubusercontent.com/10295467/54187359-b6ba1900-44f0-11e9-9c30-1bfb95f06f06.gif)

**Comment by wata727** [comment]
Looks good. However, I have some questions:

- How to exit from the console?
  - We will probably need to explain what commands are available on the console.
- Can't we scan a little faster?
  - I think that faster matching can be achieved by loading all the codebase in advance when launching the console.

**Comment by tomokinakamaru** [comment]
Thank you for your helpful comments! I will add the help message about the available commands and the cache/reload feature implemented in Querly, as you suggested.

**Comment by tomokinakamaru** [comment]
I fixed the two problems mentioned above (the help message & faster scanning):

![GOBHYVnk02](https://user-images.githubusercontent.com/10295467/54607793-98c15b00-4a92-11e9-869f-4ec33efbda4c.gif)

I also added the history recording feature, like many interactive console apps do!

**Comment by wata727** [comment]
Awesome! It's a great job :+1:
