### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by tomokinakamaru** [sider/TyScan#13]

**Comment by tomokinakamaru** [comment]
@wata727 Can you review the Dockerfile I just created in https://github.com/sider/TyScan/tree/fix/issue13 ? I copied almost all from Phinder's Dockerfile but I'm not sure if I created it correctly because I rarely use Docker... The version of TyScan is 0.1.3 in the branch `fix/issue13`, but this will be fixed to 0.1.4 after solving Issue #10 & #8.

**Comment by wata727** [comment]
Looks pretty good. By the way, it would be good to open a pull request for review.

**Comment by tomokinakamaru** [comment]
Thanks a lot! I will make a pull request for this!
