### ISSUE TITLE
Exclude node_modules/** by default

### ISSUE THREAD

**Issue by ybiquitous** [sider/TyScan#4]
This suggests excluding `node_modules/**` by default when running `tyscan scan` command.
I think most users don't want to scan files in `node_modules/`.

For example, ESLint always excludes `node_modules/**`. Its documentation [says](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) below:

> In addition to any patterns in a `.eslintignore` file, ESLint always ignores files in `/node_modules/*` and `/bower_components/*`.

(related issue: https://github.com/eslint/eslint/issues/1163)

---

By the following steps, we can see the current TyScan behavior:

```
$ cat package.json
{
  "dependencies": {
    "typescript": "^3.2.4",
    "tyscan": "github:sider/tyscan"
  }
}

$ cat tyscan.yml
rules:
  - id: foo
    pattern: "console.log(...)"
    message: No console.log

$ npx tyscan scan
node_modules/tyscan/sample/sample.ts#L2C1	console.log("...")	No console.log (foo)
```

**Comment by tomokinakamaru** [comment]
Right, scanning `node_modules` is meaningless. So I made the commit https://github.com/sider/TyScan/commit/fd311163982f7cd11bdcd3c0c7884df23aaf005b, which solves this issue. Thank you for your contribution!

**Comment by ybiquitous** [comment]
Thank you very much!
