### ISSUE TITLE
Include path in errors field in json

### ISSUE THREAD

**Issue by wata727** [sider/TyScan#9]
Currently, it does not include `path` in `errors` field when enables `--json` flag.

```
% tyscan scan broken.ts
broken.ts#L2C1: '}' expected.
% tyscan scan --json broken.ts
{"matches":[],"errors":[{"location":[2,1],"message":"'}' expected."}]}
```

**Comment by tomokinakamaru** [comment]
I added `path` to the json as you mentioned and test it in the branch `fix/issue9`. The fixed behaviour can be checked by running `./bin/tyscan.js scan --json --config test/res/ts-parse-error/tyscan.yml test/res/ts-parse-error/`. I will merge the branch `fix/issue9` and close this issue if there is no problem in it!
